### PR TITLE
added global search

### PR DESCRIPTION
**Pull request by Bibiko**

### CODE REVIEW

**Review by xrotwang — CHANGES_REQUESTED** [review]
I think that's a bit over the top, i.e. way too much code for functionality that is basically provided by google for free - considering how well indexed clld apps are.

**Comment by Bibiko** [comment]
But the `global search` is **THE** core functionality for AMSD to get quickly a subset of sticks based on any entered search term.

**Comment by xrotwang** [comment]
But then I'd simply put the whole row of the data CSV file into a tsvector column (see https://github.com/clld/clld/blob/master/src/clld/db/fts.py) and add it to the datatable.

**Comment by xrotwang** [comment]
See
- https://github.com/clld/glottolog3/blob/101c0d8f090b0d069485fca4352016b9aa51ad60/glottolog3/models.py#L352
- https://github.com/clld/glottolog3/blob/101c0d8f090b0d069485fca4352016b9aa51ad60/glottolog3/initdb.py#L406
- https://github.com/clld/glottolog3/blob/101c0d8f090b0d069485fca4352016b9aa51ad60/glottolog3/datatables.py#L232-L245

**Comment by xrotwang** [comment]
That's the "Any field" search in Glottolog: https://glottolog.org/langdoc

**Comment by Bibiko** [comment]
I also thought about such an approach, but I believe that the database load of such a ILIKE query is much much higher than a number of small and basic queries. I can try it. So far, to look for a worst case scenario "a b c d e f g h" takes on my machine ~400ms and the db load is more or less not measurable.

**Comment by xrotwang** [comment]
Well, the FTS query on >300,000 Glottolog references performs sort-of acceptable, so totally no need to think about performance for the 2000 records here ...

**Comment by Bibiko** [comment]
Ok, but this FTS approach would only run on PostgresDBs. Correct?

**Comment by Bibiko** [comment]
... and it would have the disadvantage of excluding phrase search, à la "South Wales". Correct?

**Comment by xrotwang** [comment]
Our apps all run on Postgres, so that's not a problem. Regarding phrase search: Maybe. I don't know. Google does phrase search. Anyway, for a small collection such as this one, recall seems to be more important than precision, so I wouldn't think phrase search is essential.

**Comment by Bibiko** [comment]
While building the DB one also could collect all relevant field content into one additional column which will be searched via ILIKE only. Then the query code is trivial, DB independent, and a phrase search is doable.

**Comment by xrotwang** [comment]
But that's more code, doesn't do stemming and isn't as flexible. TSVECTOR can even do proximity search, once we upgrade the servers (https://stackoverflow.com/a/25007405).

**Comment by xrotwang** [comment]
We are talking about a database of 1055 records here, so I really think "least amount of code" wins when looking for a FTS solution.

**Comment by Bibiko** [comment]
ok - its works but it's a more or less word-based search. Is there a chance to change the query to match records à la ILIKE '%term%'?

**Comment by xrotwang** [comment]
Yes, words are the tokens in this search. Why would you want substring matches?

**Comment by Bibiko** [comment]
The point here is that a lot of given tags/keywords/names are compounds (concatenated by '_') - eg sd_person, sd_person_female - thus one looks for sd_person and would find sd_person_female as well or 1882_Virchow_p33 would find all 7 sticks (fts finds nothing) -- in other words substring matching is necessary.

**Comment by xrotwang** [comment]
And if `_` is replaced with ` ` on import?

Anyway, my main point is that this is a database of 1,055 items and there's probably going to be a way to download the whole thing. So spending extra effort essentially re-implementing what a user can do in a spreadsheet program with CTRL-F seems a waste of time.

**Review by xrotwang — APPROVED** [review]
Well, I guess I still think that's way too much code; e.g. why not simply toss `'{0}.format(row)` object into the TSVECTOR column? Feel free to merge, though.

**Comment by xrotwang** [comment]
Maybe we should switch to requiring 100% statement coverage in tests. At least that's what got me to write less code :)

**Comment by Bibiko** [comment]
TSVECTOR is brilliant made for searching text written in one single natural language, but here we have not only English but also German, French mixed with English and more importantly many search items are tags, file names, etc. That's why creating the fts column is a little more expensive. And tests are coming...

**Pull request merged**
